In [1]:
import numpy as np

print("NumPy Version:", np.__version__)
arr_1d = np.array([10, 20, 30, 40, 50])

print("1D Array:", arr_1d)
print("Dimensions:", arr_1d.ndim)
print("Shape:", arr_1d.shape)
print("Data Type:", arr_1d.dtype)

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("2D Array:")
print(arr_2d)

print("Dimensions:", arr_2d.ndim)
print("Shape:", arr_2d.shape)
print("Data Type:", arr_2d.dtype)

arr_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("3D Array:")
print(arr_3d)

print("Dimensions:", arr_3d.ndim)
print("Shape:", arr_3d.shape)

arr = np.array([10, 20, 30, 40, 50])

print("First element:", arr[0])
print("Third element:", arr[2])
print("First three elements:", arr[:3])
print("Last two elements:", arr[-2:])

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(2, 3)

print("Original Array:")
print(arr)

print("\nReshaped Array:")
print(reshaped)

zeros_array = np.zeros(5)
ones_array = np.ones(5)
range_array = np.arange(1, 11)
line_array = np.linspace(0, 10, 5)

print("Zeros:", zeros_array)
print("Ones:", ones_array)
print("Arange:", range_array)
print("Linspace:", line_array)

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

numbers = np.array([1, 2, 3, 4, 5])

print("Original:", numbers)
print("Multiply by 2:", numbers * 2)
print("Square:", numbers ** 2)
print("Add 10:", numbers + 10)

numbers = np.array([10, 25, 30, 45, 50, 65])

mask = numbers > 30

print("Boolean Mask:", mask)
print("Numbers greater than 30:", numbers[mask])

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

result = arr + 10

print("Original Array:")
print(arr)

print("\nAfter Broadcasting:")
print(result)

numbers = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(numbers))
print("Mean:", np.mean(numbers))
print("Minimum:", np.min(numbers))
print("Maximum:", np.max(numbers))
print("Median:", np.median(numbers))

marks = np.array([
    [80, 75, 90],
    [65, 85, 70],
    [90, 95, 88]
])

print("Marks:")
print(marks)

print("\nTotal Marks:", np.sum(marks))
print("Average Marks:", np.mean(marks))
print("Minimum Marks:", np.min(marks))
print("Maximum Marks:", np.max(marks))
print("Median Marks:", np.median(marks))

students_marks = np.array([78, 85, 92, 67, 88, 95, 73])

print("Student Marks:", students_marks)

print("\nTotal:", np.sum(students_marks))
print("Average:", np.mean(students_marks))
print("Highest:", np.max(students_marks))
print("Lowest:", np.min(students_marks))
print("Median:", np.median(students_marks))

print("\nStudents scoring above 80:")
print(students_marks[students_marks > 80])



NumPy Version: 2.0.2
1D Array: [10 20 30 40 50]
Dimensions: 1
Shape: (5,)
Data Type: int64
2D Array:
[[1 2 3]
 [4 5 6]]
Dimensions: 2
Shape: (2, 3)
Data Type: int64
3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions: 3
Shape: (2, 2, 2)
First element: 10
Third element: 30
First three elements: [10 20 30]
Last two elements: [40 50]
Original Array:
[1 2 3 4 5 6]

Reshaped Array:
[[1 2 3]
 [4 5 6]]
Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Arange: [ 1  2  3  4  5  6  7  8  9 10]
Linspace: [ 0.   2.5  5.   7.5 10. ]
Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]
Original: [1 2 3 4 5]
Multiply by 2: [ 2  4  6  8 10]
Square: [ 1  4  9 16 25]
Add 10: [11 12 13 14 15]
Boolean Mask: [False False False  True  True  True]
Numbers greater than 30: [45 50 65]
Original Array:
[[1 2 3]
 [4 5 6]]

After Broadcasting:
[[11 12 13]
 [14 15 16]]
Sum: 150
Mean: 30.0
Minimum: 10
Maximum: 50
Median: 30.0
Marks:
[[80 75 90]
 [65 85 70]
 [90 95 88]]

T